# Generated by Django 3.0.4 on 2020-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200315_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='answer',
            new_name='answer_four',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_one',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_three',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_two',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
