# Generated by Django 3.0.4 on 2020-03-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20200315_1249'),
        ('problems', '0003_auto_20200315_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='assignments.Assignment'),
            preserve_default=False,
        ),
    ]
